### ISSUE TITLE
Splash

### ISSUE THREAD

**Issue by raphaelfabeni** [a2ad/appEducacao#5]
Pessoal, abri essa issue para podermos discutir a respeito do assunto.
Para dar o _build_ do app, utilizamos o arquivo `config.xml` para configurarmos algumas coisas, dentre elas a imagem que vai aparecer na inicialização do app ( _splash screen_ ). O problema é que na orientação _paisagem_ o splash aparece distorcido.
A sintaxe para _Android_ é a seguinte:

``` xml
<gap:splash src="../ldpi.png" gap:platform="android" gap:density="ldpi" />
<gap:splash src="../mdpi.png" gap:platform="android" gap:density="mdpi" />
<gap:splash src="../hdpi.png" gap:platform="android" gap:density="hdpi" />
<gap:splash src="../xhdpi.png" gap:platform="android" gap:density="xhdpi" />
```

Achei na web, um cara que além dessa marcação, complementa com essa, adicionando o tamanho e configurando uma imagem no formato paisagem:

``` xml
<gap:splash src="../ldpi-landscape.png" gap:platform="android" gap:density="ldpi" width="320" height="200"/>
<gap:splash src="../mdpi-landscape.png" gap:platform="android" gap:density="mdpi" width="480" height="320"/>
<gap:splash src="../hdpi-landscape.png" gap:platform="android" gap:density="hdpi" width="800" height="480"/>
<gap:splash src="../xhdpi-landscape.png" gap:platform="android" gap:density="xhdpi" width="1280" height="720"/>
```

No entanto, parece que ao dar o _build_ ele ignora a primeira sintaxe e só lê a segunda, desconfigurando o splash na orientação retrato.
Vi algumas pessoas falarem que ainda é uma deficiência do _build_ do _Phonegap_, mas eu acho que deve ter um jeito de contornar isso.
Por agora, em uma solução rápida, tinha pensado em utilizarmos um splash genérico.
Se alguém souber ou ver algo a respeito disso, só falar.

**Comment by williancarminato** [comment]
@raphaelfabeni segundo a documentação de dev do android há uma opção de orientação do aparelho, segue o link para estudo.

http://developer.android.com/guide/practices/screens_support.html#support

**Comment by raphaelfabeni** [comment]
Fala @williancarminato beleza?
Eu tinha dado uma olhada rápida nessa documentação. Mas pelo que notei, ele passa as instruções para utilização em aplicações nativas de Android que usam _Java_ . Como damos o _build_ pelo Phonegap, essas configurações não vão pra lá, apenas o que fica dentro da pasta _assets_ e que está configurado no `config.xml` .

**Comment by raphaelfabeni** [comment]
Pessoal, para essa primeira versão do protótipo, vamos deixar um splash genérico e para futuras versões, estudamos o que poderemos fazer.
Valeu, Rapha
